name: CI

on:
  push:
    branches: [v2]
  pull_request:
  workflow_dispatch:

jobs:
  linux-ci:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable", "beta", "nightly", "1.57.0"]
        include:
          - toolchain: stable
            fuzz: 1
          - toolchain: beta
            fuzz: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install packages for fuzzing
        if: runner.os == 'Linux' && matrix.fuzz == 1
        run: sudo apt-get update -y && sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc libiberty-dev

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test
        run: cargo test --verbose

      - name: Cargo check w/o default features
        run: cargo check --verbose --no-default-features

  no-std:
    name: no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: thumbv7m-none-eabi
      - name: Cargo build
        run: cargo build --verbose

  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    needs:
      - "linux-ci"
      - "no-std"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"