name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable"]
        target: ["", "--target i686-unknown-linux-musl", "--target wasm32v1-none"]

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Install 32bit target
      run: rustup target add i686-unknown-linux-musl
    - name: Install miri
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - name: Install no-std-check
      run: cargo install cargo-no-std-check
      
    - name: Build
      run: cargo build --verbose ${{ matrix.target }}
    - name: Test
      run: cargo test --verbose ${{ matrix.target }}
    - name: Clippy
      run: cargo clippy --verbose ${{ matrix.target }}
    - name: Miri
      run: cargo +nightly miri test --verbose ${{ matrix.target }}
    - name: NoStd
      run: cargo no-std-check
